### ISSUE TITLE
Running in AWS ECS

### ISSUE THREAD

**Issue by calvinlfer** [calvinlfer/akka-cluster-sample#1]
If you plan to run this in AWS ECS, you cannot take advantage of the [capabilities of Docker network](https://docs.docker.com/engine/userguide/networking). Instead, you have to expose ports to the host machine and route traffic for communication like so: 

![image](https://user-images.githubusercontent.com/14280155/28488553-b5f8e1e8-6e7a-11e7-9d57-fbc92cb81efb.png)

You will need to enable some address translation features in Akka in order to support this approach. Please see: [Akka behind NAT or in a Docker Container](http://doc.akka.io/docs/akka/current/scala/remoting.html#akka-behind-nat-or-in-a-docker-container)

The `akka.remote.netty.tcp.hostname` will be the IP of the EC2 host that is running the Docker container that can be obtained through an EC2 metadata query. 

Also see this set of [posts](https://groups.google.com/forum/#!msg/akka-user/8MJPwnSVT5g/ZY7KCbL0BQAJ) from Eric Swenson

**Comment by calvinlfer** [comment]
You can also consider using a solution like [Weave Net](https://www.weave.works/oss/net) combined with [Weave Scope](https://www.weave.works/oss/scope) to enable service discovery (via 'Micro-DNS') which gives you back *some* of the essential features of Docker network except the concept now extends to multiple physical hosts that together form a big cluster.

In this case, you wouldn't require ZooKeeper as you would use Weave Net's DNS as the bootstrapping mechanism. However, their solution seems to be geared more towards the AP side (i.e. eventual consistency) in CAP which is not what you want for critical tasks like forming a cluster (prefer strict consistency). 

See the following: 
- [Container networking with AWS ECS and Weave Net](https://www.youtube.com/watch?v=M9f2YVpR4aQ)
- [Introducing Weave Net](https://www.weave.works/docs/net/latest/introducing-weave) 
- [WeaveWorks integrations](https://www.weave.works/docs/scope/latest/ami) and [repository](https://github.com/weaveworks/integrations/tree/master/aws/ecs)

**Comment by calvinlfer** [comment]
Another solution that be considered is using `host` mode which ECS [supports](https://aws.amazon.com/about-aws/whats-new/2016/08/amazon-ec2-container-service-now-supports-networking-modes-and-memory-reservation) so containers are directly mapped to their host network. So instead of the diagram above, you will instead have

![image](https://user-images.githubusercontent.com/14280155/28489191-9ffd196c-6e8a-11e7-9347-6f06c046e6d3.png)

People have [reported](https://github.com/aws/amazon-ecs-agent/issues/185) this solution works as well

There are trade-offs with this solution with the major one being **increased performance at the cost of giving up container network isolation**.

[Docker](https://docs.docker.com/engine/userguide/networking/#default-networks) mentions:
>The `host` network adds a container on the host’s network stack. **As far as the network is concerned, there is no isolation between the host machine and the container**. For instance, **if you run a container that runs a web server on port 80 using `host` networking, the web server is available on port 80 of the host machine.**

As long as you use random ports which https://github.com/calvinlfer/akka-cluster-sample/commit/372c4b3be6158cd4fcbaa5bd61730a4b99cfad33 is doing then you should not have problems with this approach.

**Comment by calvinlfer** [comment]
More on Weave:
* [Weave Deep Dive](http://chunqi.li/2015/11/14/Weave-Network-Management-for-Docker)
* [Weave vs. others](http://chunqi.li/2015/11/15/Battlefield-Calico-Flannel-Weave-and-Docker-Overlay-Network)
* [Weave is kinda slow](http://www.generictestdomain.net/post/weave-is-kinda-slow/)
  * [Weave is now kinda fast](https://www.weave.works/blog/weave-docker-networking-performance-fast-data-path)

**Comment by calvinlfer** [comment]
We have completed the initial work of getting the Akka Cluster deployed on the AWS EC2 Container Service (ECS) Platform using the [dakka](https://github.com/LoyaltyOne/dakka) base image along with the [Docker-Mirror](https://github.com/LoyaltyOne/docker-mirror) service. 

### Problem statement ###
The problem we had when doing this was trying to figure out the IP of the ECS host and the external port of the ECS host that mapped to the Akka Clustering port inside the Docker container (which is fixed to 2551). You need this because inside the container you bind to all available network interfaces (0.0.0.0) and use port 2551. However, when other Akka Cluster nodes want to communicate with you, they need to be able to find your Akka Cluster node via the ECS host and the ECS port mapped to your container. 

### Solution ###
Akka provides us `bind-hostname` and `bind-port` so you can bind to the correct network interface(s) and port and advertise to others the external IP and port. 

#### Determining the external ECS host port mapped to your Docker container ####
In order to find out the ECS port mapped to your Docker container's port, you need to be able to use the ECS host's docker daemon to find the mappings which involves running a [Docker-in-Docker setup](https://medium.com/lucjuggery/about-var-run-docker-sock-3bfd276e12fd) where you install Docker within your Docker container and volume mount `/var/run/docker.sock` from the ECS host into your Docker container (mount at the same location) to get access to the mappings. This solves the problem of obtaining your port mappings but we have to still address the part where we obtain the ECS host IP. We would also like to mention that you now need to install Docker and run this Docker-in-Docker setup in each container which is clunky. We will discuss how we fix this after talking about fixing the ECS host IP. 

#### Determining the ECS host IP hosting your Docker container ####
You can use the ec2-metadata query to obtain the IPV4 address of the host. The way we chose to solve this was to do this directly during the creation of the ECS cluster in CloudFormation. When we configure our EC2 instances that belong to the ECS cluster, we run a script in the CloudFormation Init script
```bash
ip=$(curl http://169.254.169.254/latest/meta-data/local-ipv4)
echo $ip > /etc/hostip
```

We store the information in a file that will exist on every EC2 instance that is part of the ECS cluster. So you can mount this file into your container as well to obtain the ECS host IP that you advertise to your peers. 

### Refinement ###
As we hinted earlier, running Docker-in-Docker inside every Akka Cluster Node is clunky because of the volume mounts for both the `docker.sock` and `hostip` file. Also installing Docker will bloat the image size. Rather than doing this in all Akka Cluster application Docker containers, we created [Docker-Mirror](https://github.com/LoyaltyOne/docker-mirror) to isolate this specialized logic to a single place. 

Docker-Mirror is a Node.JS REST server that is designed to answer two questions:
- **What is my ECS host IP**?
- Given my Docker container port, **what is the ECS external host port that is mapped to my Docker container port** (optionally providing the interface and port if necessary using all interfaces by default)?

We ensure that Docker-Mirror is running on every single ECS host on the bridge network and has the volume mounts to `docker.sock` and the `hostip` file. Again, we set this up in CloudFormation as we need to ensure this service runs on every single EC2 instance that is part of the cluster on startup. This is the easiest way to guarantee that this happens. 
```bash
docker run -d --name docker-mirror -p 9001:9000 --restart always -v /var/run/docker.sock:/var/run/docker.sock -v /etc/hostip:/etc/hostip loyaltyone/docker-mirror:0.1.2
```

We give it a restart policy to ensure that if the container goes down, it will be restarted. With Docker-Mirror in place, we simplify the [setup](https://github.com/LoyaltyOne/dakka/blob/master/bootstrap) of our Akka Cluster application Docker images. On startup, we obtain the gateway IP to the bridge network and call out to Docker-Mirror to answer our questions:
```bash
DOCKER_MIRROR_HOST=$(/sbin/ip route|awk '/default/ { print $3 }')
DOCKER_MIRROR_PORT=${MIRROR_PORT:-9001}
DOCKER_MIRROR="http://$DOCKER_MIRROR_HOST:$DOCKER_MIRROR_PORT"

export HOST_IP=$(curl $DOCKER_MIRROR/hostip)
export HOST_PORT=$(curl $DOCKER_MIRROR/container/$HOSTNAME/port/$APP_PORT)   
```

Note that the `APP_PORT` is your Akka Clustering port which we fix to `2551`. 

We are now able to utilize this information in our HOCON configuration
```hocon
akka {
  remote {
    enabled-transports = ["akka.remote.netty.tcp"]
    netty.tcp {
      bind-hostname = 0.0.0.0
      bind-port = 2551

      hostname = ${?HOST_IP}
      port = ${?HOST_PORT}
    }
  }
}
```

With this in place, when our Akka Cluster applications start up, we use ConstructR backed by ZooKeeper to register and determine if existing seed nodes exist and form the cluster and this configuration correctly does the mapping from the Docker containers to their ECS hosts allowing for cluster communication and successful operation.

**Comment by calvinlfer** [comment]
The reason why I haven't closed this issue yet is because we will do a blog post detailing what is needed to get this set up

**Comment by AlbertoMonteiro** [comment]
Nice!!

**Comment by calvinlfer** [comment]
See [Medium article](https://medium.com/@ukayani/deploying-clustered-akka-applications-on-amazon-ecs-fbcca762a44c)

**Comment by rmmeans** [comment]
This is great stuff, thanks for your work here and writing up the post!

Folks should also be aware of the new native networking mode for ECS containers now as well though: https://aws.amazon.com/blogs/compute/introducing-cloud-native-networking-for-ecs-containers/  in addition, running their containers on ECS with fargate. Both of these modes put your container right right onto the VPC with an IP from your VPC subnet (an ENI is given to each container).  This makes dealing with Akka clustering on ECS almost identical to dealing with it on straight EC2s.

**Comment by calvinlfer** [comment]
@rmmeans The reinvent releases this year essentially deprecates ECS. Fargate looks really interesting with VPC networking so you don't have to jump through any hoops. How do you feel about EKS (Kubernetes) vs. Fargate?

**Comment by rmmeans** [comment]
@calvinlfer Sorry - just saw this reply! I think it really comes down to your needs and also costs. We run some workloads on Fargate, some on Kub on AWS via KOPS, and looking to spin up an EKS. 

This was a great podcast on software engineering daily with the head of compute at AWS: https://softwareengineeringdaily.com/2018/10/19/aws-containers-with-deepak-singh/  He covers some of the reasons why customers might choose one or another.
